// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYe9p9A-9ksf2OvLeRw-tZU9OCV7dsNx0',
    appId: '1:75095310994:web:24c701e3ad92fcfc135c4b',
    messagingSenderId: '75095310994',
    projectId: 'kitahack-rempits',
    authDomain: 'kitahack-rempits.firebaseapp.com',
    storageBucket: 'kitahack-rempits.appspot.com',
    measurementId: 'G-8LE9X81LWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMVBwwsoHTKURlU4AgyWKgQW73jmgRZZg',
    appId: '1:75095310994:android:bc17414af8c2ad74135c4b',
    messagingSenderId: '75095310994',
    projectId: 'kitahack-rempits',
    storageBucket: 'kitahack-rempits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS673Yt-mKdrpr-Fb2CorWizJPb94yIK8',
    appId: '1:75095310994:ios:111b65ccc24ad911135c4b',
    messagingSenderId: '75095310994',
    projectId: 'kitahack-rempits',
    storageBucket: 'kitahack-rempits.appspot.com',
    iosBundleId: 'com.example.gardenio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS673Yt-mKdrpr-Fb2CorWizJPb94yIK8',
    appId: '1:75095310994:ios:cab0da3a0ad792bb135c4b',
    messagingSenderId: '75095310994',
    projectId: 'kitahack-rempits',
    storageBucket: 'kitahack-rempits.appspot.com',
    iosBundleId: 'com.example.gardenio.RunnerTests',
  );
}
